// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZB2njSl4jzYV6Xyjef-uvNqJCxW9f4xs',
    appId: '1:383957463244:web:57dd82832c99e41608d269',
    messagingSenderId: '383957463244',
    projectId: 'complete-flutter-app-90e73',
    authDomain: 'complete-flutter-app-90e73.firebaseapp.com',
    storageBucket: 'complete-flutter-app-90e73.firebasestorage.app',
    measurementId: 'G-2DD54QD49X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_BNGPSsTc3JF8AeoKT_WwgaMiLQdmkig',
    appId: '1:383957463244:android:7901d2ced9fe493d08d269',
    messagingSenderId: '383957463244',
    projectId: 'complete-flutter-app-90e73',
    storageBucket: 'complete-flutter-app-90e73.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZB2njSl4jzYV6Xyjef-uvNqJCxW9f4xs',
    appId: '1:383957463244:web:4afff9c5019f8aae08d269',
    messagingSenderId: '383957463244',
    projectId: 'complete-flutter-app-90e73',
    authDomain: 'complete-flutter-app-90e73.firebaseapp.com',
    storageBucket: 'complete-flutter-app-90e73.firebasestorage.app',
    measurementId: 'G-9DS9R8KPTL',
  );
}
